export const productCategories = [
    "Buddha",
    "Shiv",
    "Mukhalingam",
    "Ardhanareshwara",
    "Nandi",
    "Nataraja",
    "Ganesha",
    "Krishna",
    "Ram",
    "Hanuman",
    "Vishnu",
    "Garuda",
    "Durga",
    "Tirupati Balaji",
    "Brass Treasure Boxes",
    "Brass Urli",
    "Brass tree Kalpavriksha",
    "Brass Showpieces",
    "Brass Diyas and Lamps",
    "Brass Bells",
    "Brass Prabhavalis",
    "Elephants",
    "Wall Hangings",
    "Brass Shankh",
    "Intricate Small Superfine Brass Idols",
    "Copper Idols",
    "Pure Bronze Solid Idols from South India",
    "Wooden Wall Hangings with Brass Artifacts",
    "Vintage Statues Sculptures",
    "Timeless Indonesian Style Bronze Artifacts",
    "Master Pieces",
    "Hand Painted Brass Idols",
  ];
  